mysite/catalog/urls.py
from django.conf.urls import url

from . import views

app_name = 'catalog'
urlpatterns = [
	url(r'^$', views.catalog_home, name="home"),
	#url(r'^(?P<catalog_id>[0-9]+)$', views.catalog_detail, name='catalog_detail'),
	url(r'^(?P<catalog_id>[\d+]+)$', views.catalog_detail, name='detail'),
]

mysite/default_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^contacts$', views.contacts, name='contacts'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^catalog/', include('catalog.urls')),
    url(r'^', include('default_app.urls')),
    url(r'^admin/', admin.site.urls),

]

mysite/catalog/models.py
from django.db import models

class Catalog(models.Model):
	title = models.CharField(max_length=150)
	image = models.ImageField(upload_to='catalog_images', blank=True)
	discription = models.TextField()

	def __str__(self):
		return self.title

mysite/default_app/models.py
from django.db import models

# Create your models here.

mysite/catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Catalog
#from django.http import HttpResponse

def catalog_home(request):
    catalog_list = Catalog.objects.all()
    paginator = Paginator(catalog_list, 1) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        catalog = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        catalog = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        catalog = paginator.page(paginator.num_pages)
    if page == 1:
    	return redirect('catalog:home', permanent=True)
    context = {
    	'page_header': 'Catalog page',
    	'catalog': catalog,
    }
    return render(request, 'catalog/catalog.html', context)
	

def catalog_detail(request, catalog_id):
	catalog_item = get_object_or_404(Catalog, pk = catalog_id)
	context = {
	'page_header': catalog_item.title ,
    'catalog_item': catalog_item,
	}
	return render(request, 'catalog/catalog_detail.html', context)
	

mysite/default_app/views.py
from django.shortcuts import render
from catalog.models import Catalog 
from django.http import HttpResponse


def home(request):
    context = {
    	'page_header': 'home page title',
    	'catalog': Catalog.objects.all(),
    }
    return render(request, 'default_app/home.html', context)

def contacts(request):
	contacts_form_data = {}
	
	if request.method == 'POST':
		#contacts_form_data = request.POST
		user_name = request.POST.get('user_name')
		user_email = request.POST.get('user_email')
		message = request.POST.get('message')

		contacts_form_data.update({'user_name': user_name, 'user_email': user_email, 'message': message})
	context = {
		'page_header':'Contacts form',
		'contacts_form_data': contacts_form_data,
	}
	return render(request, 'default_app/contacts_form.html', context)

mysite/catalog/templates/catalog/catalog.html
{% extends 'base.html' %}

{% block content %}
	{% for catalog_item in catalog %}
		<div>
			<h2><a href="{% url 'catalog:detail' catalog_item.id %}">{{catalog_item.title}}</a></h2>
			<div>
				{{catalog_item.discription| truncatechars:200}}
			</div>
		</div>
	{% endfor  %}

<!--	<div class="pagination">
    	<span class="step-links">
        	{% if catalog.has_previous %}
            	<a href="?page={{ catalog.previous_page_number }}">previous</a>
        	{% endif %}

        	<span class="current">
            	Page {{ catalog.number }} of {{ catalog.paginator.num_pages }}.
        	</span>

        	{% if catalog.has_next %}
            	<a href="?page={{ catalog.next_page_number }}">next</a>
        	{% endif %}
    	</span>
	</div>-->

	<div class="text-center">
		<ul class="pagination">
			{% if catalog.number > 1 %}
				<li><a href="?page=1">&laquo; First page</a></li>
			{% else %}
				<li class="disabled"><a href="">&laquo; First page</a></li>
			{% endif %}

			{% if catalog.has_previous %}
				<li><a href="?page={{ catalog.previous_page_number }}">&laquo; Prev</a></li>
			{% else %}
				<li class="disabled"><a href="">&laquo; Prev </a></li>
			{% endif %}

			{% if catalog.number > 1 %}
				{% for page in catalog.paginator.page_range %}
					<li class="{% if catalog.number == page %}active{% endif %}"><a href="?page={{ page }}">{{ page }}</a></li>
				{% endfor %}
			{% endif %}

			{% if catalog.has_next %}
				<li><a href="?page={{ catalog.next_page_number}}">Next &raquo;</a></li>
			{% else %}
				<li class="disabled"><a href="">Next &raquo;</a></li>
			{% endif %}

			{% if catalog.number < catalog.paginator.num_pages %}
				<li><a href="?page={{ catalog.paginator.num_pages }}">Last page &raquo;</a></li>
			{% else %}
			<li class="disabled"><a href="">Last page &raquo;</a></li>
			{% endif %}
		</ul>
	</div>
{% endblock %}

mysite/catalog/templates/catalog/catalog_detail.html
{% extends 'base.html' %}

{% block content %}
	<div>
		<a class="btn btn-primary" href="{% url 'catalog:home' %}">&larr; Retirn back to Catalog</a><br><br>
	</div>
	<div>
		{{ catalog_item.discription }}
	</div>
{% endblock %}

mysite/default_app/templates/default_app/contacts_form.html
{% extends 'base.html' %}

{% block content %}
	{{ contacts_form_data }}

	<form method="post">
		{% csrf_token %}
		<div class="form-group">
    		<label for="user_name">Name</label>
    		<input type="text" class="form-control" id="user_name" name="user_name" placeholder="What is your name">
  		</div>

  		<div class="form-group">
    		<label for="user_email">Email</label>
    		<input type="email" class="form-control" id="user_email" name="user_email" placeholder="Your email adress">
  		</div>

  		<div class="form-group">
    		<label for="message">Message</label>
    		<textarea id="message" name="message" class="form-control" rows="5"></textarea>
  		</div>

  		<button type="submit" class="btn btn-default">Submit</button>
	</form>
{% endblock %}

mysite/default_app/templates/default_app/home.html
{% extends 'base.html' %}
{% block content %}
			
	{% for cat_item in catalog %}
	<div>
		<h1>{{ cat_item.title }}</h1>
		<div>{{ cat_item.discription }}</div>
	</div>
	{% endfor %}
		
{% endblock %}

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	<title>{% if page_header %}{{ page_header}}{% endif %} | Django sandbox project</title>
	<script src="https://cdn.jsdelivr.net/g/jquery@3.2.1,bootstrap@4.0.0-alpha.6"></script>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <img src="{% static 'images/django-logo.png' %}">
	<div class="container">
		{% if page_header %}
		<div  class="page-header">
			<h1>{{ page_header}}</h1>
		</div>
		{% endif %}
	</div>
	{% block content %}{% endblock %}
	
</body>
</html>